name: Auto Build Action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  steps:
    runs-on: ubuntu-22.04
    steps:
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18.3
        id: go
      - name: check out
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: bash ./../../build-all.sh

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
